
export const allEvents = [
    {
      id: 1,
      title: "Festival International de Musique",
      artist: "ARTISTE PRINCIPAL",
      date: "SAMEDI 28 JUIN",
      time: "20:00",
      location: "Carthage",
      venue: "Amphithéâtre",
      image:
        "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
      category: "Musique",
      price: "45 TND",
      rating: "4.9", 
      isHot: true,
    },
    {
      id: 2,
      title: "Spectacle de Danse",
      artist: "COMPAGNIE DANSE",
      date: "DIMANCHE 29 JUIN",
      time: "19:00",
      location: "Tunis",
      venue: "Théâtre Municipal",
      image:
        "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80",
      category: "Danse",
      price: "30 TND",
      rating: "4.9", 
      isHot: true,
    },
    {
      id: 3,
      title: "Concert Jazz",
      artist: "JAZZ ENSEMBLE",
      date: "LUNDI 30 JUIN",
      time: "21:00",
      location: "Sousse",
      venue: "Plage Corniche",
      image:
        "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80",
      category: "Jazz",
      price: "55 TND",
      rating: "4.9", 
      isHot: true,
    },
    {
      id: 4,
      title: "Soirée Rock",
      artist: "ROCK BAND",
      date: "MARDI 1 JUILLET",
      time: "20:30",
      location: "Nabeul",
      venue: "Stade Municipal",
      image:
        "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80",
      category: "Rock",
      price: "35 TND",
      rating: "4.9", 
      isHot: true,
    },
    {
      id: 5,
      title: "Concert Pop",
      artist: "POP STAR",
      date: "MERCREDI 2 JUILLET",
      time: "21:00",
      location: "Monastir",
      venue: "Arena Hall",
      image:
        "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80",
      category: "Pop",
      price: "60 TND",
      rating: "4.9", 
      isHot: true,
    },
    {
      id: 6,
      title: "Festival Électro",
      artist: "DJ ELECTRONIC",
      date: "JEUDI 3 JUILLET",
      time: "22:00",
      location: "Djerba",
      venue: "Beach Stage",
      image:
        "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
      category: "Électro",
      price: "70 TND",
      rating: "4.9", 
    isHot: true,
    },
  ];
  